vich_uploader:
    db_driver: orm

    mappings:
        partners_logo:
            uri_prefix: '%app.path.partners_logo%'
            upload_destination: '%kernel.project_dir%/public%app.path.partners_logo%'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            delete_on_remove: true
            delete_on_update: true
