#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_sav_pdf:
  path: '/sav/pdf/{id}'
  controller: 'App\Controller\ServiceApresVenteController::generatePdf'
  methods: ['GET']